exportarrImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/exportarr
  tag: v2.0.1@sha256:727e7bc8f2f0934a2117978c59f4476b954018b849a010ea6cfb380bd6539644
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/radarr
  tag: 6.0.4@sha256:a360633a3682d41e96f71a07ff36ecbdf2394a9628465b84b0a8437087715b41
metrics:
  main:
    enabled: true
    endpoints:
    - path: /metrics
      port: metrics
    prometheusRule:
      enabled: false
    targetSelector: metrics
    type: servicemonitor
persistence:
  config:
    enabled: true
    targetSelector:
      main:
        exportarr:
          mountPath: /config
          readOnly: true
        main:
          mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 7878
  metrics:
    enabled: '{{ .Values.metrics.main.enabled }}'
    ports:
      metrics:
        enabled: true
        port: 7879
    type: ClusterIP
workload:
  main:
    podSpec:
      containers:
        exportarr:
          args:
          - radarr
          enabled: '{{ .Values.metrics.main.enabled }}'
          env:
            CONFIG: /config/config.xml
            INTERFACE: 0.0.0.0
            PORT: '{{ .Values.service.metrics.ports.metrics.port }}'
            URL: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname"
              $) .Values.service.main.ports.main.port }}'
          imageSelector: exportarrImage
          probes:
            liveness:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
            readiness:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
            startup:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
        main:
          env:
            RADARR__AUTH__METHOD: ''
            RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
            RADARR__SERVER__PORT: '{{ .Values.service.main.ports.main.port }}'
          probes:
            liveness:
              enabled: true
              path: /ping
              type: http
            readiness:
              enabled: true
              path: /ping
              type: http
            startup:
              enabled: true
              path: /ping
              type: http
