image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/tautulli/tautulli
  tag: v2.16.1
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
workload:
  main:
    podSpec:
      containers:
        main:
          args:
          - --config
          - /config/config.ini
          - --datadir
          - /config
          command:
          - python
          - Tautulli.py
