exportarrImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/exportarr
  tag: v2.0.1
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/home-operations/bazarr
  tag: 1.5.6
metrics:
  main:
    apiKey: ''
    enabled: false
    endpoints:
    - path: /metrics
      port: metrics
    targetSelector: metrics
    type: servicemonitor
persistence:
  config:
    enabled: true
    targetSelector:
      main:
        exportarr:
          mountPath: /config
          readOnly: true
        main:
          mountPath: /config
portal:
  open:
    enabled: true
service:
  main:
    ports:
      main:
        port: 6767
        protocol: http
        targetPort: 6767
  metrics:
    enabled: '{{ .Values.metrics.main.enabled }}'
    ports:
      metrics:
        enabled: true
        port: 7879
    type: ClusterIP
workload:
  main:
    podSpec:
      containers:
        exportarr:
          args:
          - bazarr
          enabled: '{{ .Values.metrics.main.enabled }}'
          env:
            APIKEY: '{{ .Values.metrics.main.apiKey }}'
            INTERFACE: 0.0.0.0
            PORT: '{{ .Values.service.metrics.ports.metrics.port }}'
            URL: '{{ printf "http://%v:%v" (include "tc.v1.common.lib.chart.names.fullname"
              $) .Values.service.main.ports.main.port }}'
          imageSelector: exportarrImage
          probes:
            liveness:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
            readiness:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
            startup:
              enabled: true
              path: /healthz
              port: '{{ .Values.service.metrics.ports.metrics.port }}'
              type: http
